apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pgbouncer.configFile" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |-
{{ include "pgbouncer.ini" . | indent 4 }}