{{- if .Values.enabled -}}{{/* ENABLED */}}
{{-   if eq (include "gitlab.ingress.enabled" $) "true" -}}{{/* INGRESS ENABLED */}}
{{-     include "webservice.datamodel.prepare" $ -}}
{{-     range $.Values.deployments -}}{{/* RANGE DEPLOYMENTS */}}
{{/*
From here on:
- `.` is `.deployments.xyz` value
- `.name` is the key (xyz)
*/}}
{{-       $global := $.Values.global }}
{{-       $hostname := $global.hosts.gitlab.hostnameOverride | default (include "gitlab.gitlab.hostname" $) -}}
{{-       $ingressName := include "webservice.fullname.withSuffix" . -}}
{{-       $tlsSecret := include "webservice.tlsSecret" (dict "root" $ "local" $.Values.ingress) -}}
{{-       $ingressCfg := dict "global" $global.ingress "context" $ "local" .ingress -}}
{{-       include "webservice.ingress.template" (dict "root" $ "deployment" . "ingressCfg" $ingressCfg "host" $hostname "name" $ingressName "tlsSecret" $tlsSecret) }}
{{-       if and .ingress.assetsShim (eq "nginx" (include  "gitlab.ingress.provider" $ingressCfg)) }}
{{-         $ingressName = printf "%s-assets" $ingressName -}}
{{-         $assetsIngressCfg := deepCopy $ingressCfg -}}
{{-         $_ := set $assetsIngressCfg.local "path" "/assets" -}}
{{-         $_ := set $assetsIngressCfg.local.annotations "nginx.ingress.kubernetes.io/service-upstream" "false" -}}
{{-         $_ := set $assetsIngressCfg.local.annotations "nginx.ingress.kubernetes.io/proxy-next-upstream" "error timeout http_500 http_502 http_503 http_404" -}}
{{-         $_ := set $assetsIngressCfg.local.annotations "nginx.ingress.kubernetes.io/proxy-next-upstream-timeout" "0" -}}
{{-         $_ := set $assetsIngressCfg.local.annotations "nginx.ingress.kubernetes.io/proxy-next-upstream-tries" "10" -}}
{{-         $_ := set $assetsIngressCfg.local "proxyBodySize" "1m" -}}
{{-         include "webservice.ingress.template" (dict "root" $ "deployment" . "ingressCfg" $assetsIngressCfg "host" $hostname "name" $ingressName "tlsSecret" $tlsSecret) }}
{{-       end }}
{{-       if $.Values.extraIngress.enabled }}
{{-         $hostname = $.Values.extraIngress.hostname | default $hostname -}}
{{-         $_ := set $ingressCfg "local" .extraIngress -}}
{{-         $ingressName = printf "%s-extra" $ingressName -}}
{{-         $tlsSecret = include "webservice.tlsSecret" (dict "root" $ "local" $.Values.extraIngress) -}}
{{-         if $tlsSecret }}
{{-           $tlsSecret = printf "%s-extra" $tlsSecret }}
{{-         end }}
{{-         include "webservice.ingress.template" (dict "root" $ "deployment" . "ingressCfg" $ingressCfg "host" $hostname "name" $ingressName "tlsSecret" $tlsSecret) }}
{{-       end }}
{{-     end -}}{{/* RANGE DEPLOYMENTS */}}
{{-   end -}}{{/* INGRESS ENABLED */}}
{{- end -}}{{/* ENABLED */}}
