.review_app_common:
  stage: review
  variables:
    AGENT_NAME: "gke125-ci-cluster" # connect to 1.25 cluster until we have a dedicated cluster
  environment:
    name: gke125_vcluster/${VCLUSTER_K8S_VERSION}/$CI_COMMIT_REF_SLUG
    auto_stop_in: 1 hour
  before_script:
    - source scripts/ci/vcluster.sh
  rules:
    - if: '$PIPELINE_TYPE =~ /MR_PIPELINE$/'
    - if: '$PIPELINE_TYPE =~ /FEATURE_BRANCH_PIPELINE$/'

.review_app_template:
  extends: .review_app_common
  script:
    - cluster_connect
    - kubectl version
    - vcluster_create
    - vcluster_connect
    - kubectl version

.stop_review_app_template:
  extends: .review_app_common
  dependencies: []
  script:
    - cluster_connect
    - vcluster_delete
  environment:
    action: stop

# Below, create two jobs for each Kubernetes version:
#  - one to create the environment
#  - one to stop the environment

review_gke_k8s_126:
  extends: .review_app_template
  variables:
    VCLUSTER_K8S_VERSION: "1.26"
  environment:
    on_stop: stop_review_gke_k8s_126

stop_review_gke_k8s_126:
  extends: .stop_review_app_template
  variables:
    VCLUSTER_K8S_VERSION: "1.26"
